# Generated by Django 5.0 on 2024-01-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='imgplanta',
            field=models.CharField(default='imgs/img1.png', max_length=255),
        ),
    ]
