# Generated by Django 5.0 on 2024-01-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='tipo_planta',
            new_name='tipo_planta_id',
        ),
    ]
