# Generated by Django 5.0 on 2024-01-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tipo_planta_planta_tipo_planta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplanta',
            name='estado',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoplanta',
            name='nombre',
            field=models.CharField(default='Tipo Planta', max_length=50),
        ),
    ]
