# Generated by Django 5.0 on 2024-01-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tipoplanta_estado_alter_tipoplanta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplanta',
            name='nombre',
            field=models.CharField(default='Tipo Planta', max_length=100),
        ),
    ]
