# Generated by Django 5.0 on 2024-01-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tipoplanta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='beneficios',
            field=models.TextField(default='Plantita bonito mi amor'),
        ),
    ]
