# Generated by Django 5.0 on 2024-01-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_planta_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='cuidados',
            field=models.TextField(default='Plantita bonito mi amor'),
        ),
        migrations.AddField(
            model_name='planta',
            name='riego_abono',
            field=models.TextField(default='Plantita bonito mi amor'),
        ),
        migrations.AddField(
            model_name='planta',
            name='tierra',
            field=models.TextField(default='Plantita bonito mi amor'),
        ),
        migrations.AddField(
            model_name='planta',
            name='ubi_luz',
            field=models.TextField(default='Plantita bonito mi amor'),
        ),
    ]
