# Generated by Django 5.0 on 2024-01-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_planta_cuidados_planta_riego_abono_planta_tierra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='dificultad',
            field=models.TextField(default='Fácil de cuidar'),
        ),
        migrations.AddField(
            model_name='planta',
            name='lugara',
            field=models.TextField(default='Mesa de Centro'),
        ),
        migrations.AddField(
            model_name='planta',
            name='lugarb',
            field=models.TextField(default='Habitación'),
        ),
        migrations.AddField(
            model_name='planta',
            name='lugarc',
            field=models.TextField(default='Interior'),
        ),
        migrations.AddField(
            model_name='planta',
            name='tamano',
            field=models.TextField(default='Grande'),
        ),
    ]
