# Generated by Django 5.0 on 2024-01-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_planta_imgplantapartecinco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('material', models.CharField(default='Material de la maceta', max_length=100)),
                ('medidasmaceta', models.CharField(default='16cm (alto) x 20cm (ancho)', max_length=200)),
                ('incluye', models.CharField(default='Maceta de arcilla, plato y asesoramiento para cuidarla.', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('imgmaceta', models.CharField(default='imgs/maceta_img1.jpeg', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FotosPlantaMaceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidasmacetaplanta', models.CharField(default='33cm (alto) x 30cm (ancho)', max_length=200)),
                ('imagen', models.ImageField(upload_to='fotos_planta_maceta/')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planta')),
                ('maceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maceta')),
            ],
        ),
    ]
