# Generated by Django 5.0 on 2024-01-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_maceta_fotosplantamaceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosplantamaceta',
            name='imagen',
            field=models.CharField(default='imgs/imgplantaparteseis.jpeg', max_length=255),
        ),
    ]
