# Generated by Django 5.0 on 2024-02-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_fotosplantamaceta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
